- hosts: cluster
  remote_user: root
  vars:
    venv_dir: /tmp/libertem-bench-venv/
    checkout_dir: /tmp/libertem-bench/
  tasks:
    - name: cleanup running dask workers
      command: killall dask-worker
      ignore_errors: yes
    - name: remove virtualenv
      file:
        path: "{{ venv_dir }}"
        state: absent
    - name: remove git checkout
      file:
        path: "{{ checkout_dir }}"
        state: absent
    - name: umount ansible tmpfs
      command: umount "{{ item }}"
      with_items:
        - /root/.ansible_async
        - /root/.ansible
        - /home/benchmark/
      ignore_errors: yes
