name: Collect and Render

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Workflow run ID to download artifact from'
        required: true
        type: string
      source_repo:
        description: 'owner/repo of the source repository'
        required: true
        type: string

concurrency:
  group: collect-and-render
  cancel-in-progress: false

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download artifact
        env:
          GH_TOKEN: ${{ secrets.BENCH_GH_TOKEN }}
        uses: actions/download-artifact@v4
        with:
          name: artifact
          github-token: ${{ secrets.BENCH_GH_TOKEN }}
          repository: ${{ github.event.inputs.source_repo }}
          run-id: ${{ github.event.inputs.run_id }}
          path: artifact_contents

      - name: List some files
        run: ls -la && find