name: Collect and Render

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Workflow run ID to download artifact from'
        required: true
        type: string
      source_repo:
        description: 'owner/repo of the source repository'
        required: true
        type: string

concurrency:
  group: collect-and-render
  cancel-in-progress: false

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download artifact
        env:
          GH_TOKEN: ${{ secrets.BENCH_GH_TOKEN }}
        uses: actions/download-artifact@v4
        with:
          name: artifact
          github-token: ${{ secrets.BENCH_GH_TOKEN }}
          repository: ${{ github.event.inputs.source_repo }}
          run-id: ${{ github.event.inputs.run_id }}
          path: artifact_contents

      - name: List all files
        run: ls -la && find

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Collect new benchmarks
        run: |
            python3 -m venv venv \
            && ./venv/bin/pip install click \
            && ./venv/bin/python collect.py artifact_contents/*.zip \
            --repo-name ${{ github.event.inputs.source_repo }} --dest-folder ./collected

      - name: Prepare git for committing
        run: git config --global user.email a.clausen@fz-juelich.de && git config --global user.name "GitHub Actions"

      - name: Commit newly collected benchmarks
        run: git add ./collected && git commit -m "Add benchmark from ${{ github.event.inputs.source_repo }}" && git push